In [2]:
import numpy as np

In [9]:
# 作业1
array1 = np.arange(1,13).reshape(3,4)
print(array1)
print("数组形状：",array1.shape)
print("数组维度：",array1.ndim)
print("数据类型：",array1.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
数组形状： (3, 4)
数组维度： 2
数据类型： int32


In [4]:
print("元素乘2:",array1 * 2)

元素乘2: [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [5]:
arr = array1.reshape(4,3)
print("重塑后的数组：",arr)

重塑后的数组： [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
# 作业2
array2 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])
print(array2[1,])
print(array2[:,2])
print("第1、2行，第3、4列",array2[:2,1:3])
array2[array2 > 10] = 0
print("替换后的数组：")
print(array2)

[5 6 7 8]
[ 3  7 11 15]
第1、2行，第3、4列 [[2 3]
 [6 7]]
替换后的数组：
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  0  0]
 [ 0  0  0  0]]


In [10]:
# 作业3
array_A = np.arange(1,7).reshape(3,2)
array_B = np.array([10, 20])
array_A + array_B
array_A * array_B
np.dot(array_A, array_B)  # 或 A @ B

array([ 50, 110, 170])